### ISSUE TITLE
Odkazy na pobočky

### ISSUE THREAD

**Issue by ondrahlavac** [ohweb/loterie-korunka-chance-sk#6]
Odkazy na pobočky udělat proklikávací na web Korunka.eu

**Comment by ondrahlavac** [comment]
Tohle dle mého názoru nechceme.
Aktuálně se nedá na pobočky odkazovat ani na web Korunky ani na web Chance.

IMHO: Vývoj této funkcionality by byl prohibitivně drahý.

**Comment by babant** [comment]
Nebude se řešit

**Comment by ondrahlavac** [comment]
Nebudeme řešit.
